# Generated by Django 4.0.1 on 2023-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
